class NativeFunType:
    TOSTRING = "TOSTRING"
    TOFIXED = "TOFIXED"
    TOEXPONENTIAL = "TOEXPONENTIAL"
    TOLOWERCASE = "TOLOWERCASE"
    TOUPPERCASE = "TOUPPERCASE"
    SPLIT = "SPLIT"
    CONCAT = "CONCAT"
